### ISSUE TITLE
Update auf 2.0.1 wird nicht installiert.

### ISSUE THREAD

**Issue by deltapapa01** [coolcat-creations/mod_ccctwoclick#10]
Hi Elisa,
ich habe irgendwie auf meinen Seiten ein Problem mit dem Update.
Es wird als Update angezeigt (auch in myjoomla.com und dem Joomla Toolkit), ich kann es auch installieren (ohne Fehlermeldung) aber nach dem leeren des Caches und dem anschließenden Suchen nach Altualisierungen wird mir das Update auf Version 2.0.1 wieder angezeigt.
Auch wird mir nach dem Update unter Verwaltung / Module noch die Version 2.0.0 angezeigt.

Also irgendwie scheint sich da ein Fehler eingeschlcihen zu haben :-)

Viele Grüße,
deltapapa

**Comment by coolcat-creations** [comment]
Hallo @deltapapa01 danke für den Hinweis, das Update war erfolgreich aber die XML war falsch. Jetzt ist der Fehler behoben :)
