### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Alkahna** [coolcat-creations/mod_ccctwoclick#11]
Hi,
I wanted to ask if it was possible to add a link to the text before/after the click?
The field just ignores html code for now.
I would like to be able to link to something like: https://www.google.de/intl/de/policies/privacy/. in here.

**Comment by Engholm** [comment]
I agree with the suggestion and would also appreciate it if simple HTML (incl. <a href="..") is possible in the content field. It should be possible to link to the privacy policy of the external site.

**Comment by coolcat-creations** [comment]
I added an option to select and display a privacy link :)
