### ISSUE TITLE
Add option to disable the header

### ISSUE THREAD

**Issue by nakami** [coolcat-creations/mod_ccctwoclick#13]
Right now, you cannot disable the header to display. It uses the title of the module.

**Comment by coolcat-creations** [comment]
Hi @nakami sorry for the very late reply - what do you mean by that? The title can be disabled in the module settings (Hide Title)

**Comment by ChristineWk** [comment]
![Screenshot 2022-06-10 195505](https://user-images.githubusercontent.com/15275917/173125358-b135872d-e67e-441a-b95b-64cd41c121bd.png)

**Comment by nakami** [comment]
I'm sorry. It's been some time and the product owner decided to not include a respective google maps iframe.
Sadly, I don't have any related working copies to check again. I should've been more elaborate!

Feel free to close this issue.

**Comment by coolcat-creations** [comment]
ok :-) Sorry anyway for the late reply I have issues with GitHub notifications somehow :)
