### ISSUE TITLE
Hi Coolcate-Creations

### ISSUE THREAD

**Issue by saovry** [coolcat-creations/mod_ccctwoclick#9]
I have one question about your module_ccctwoclick

1. Is there possible that allow first click to open Google Adsense and second click load my website? if someone go to my website so it will not see my website yet, it seems some thing popup and when guest/user click on it so it will open google Adsense and then they can to my website.

I post in Joomla forum but there is no one can advice me
here https://forum.joomla.org/viewtopic.php?f=715&t=969867

thank

**Comment by coolcat-creations** [comment]
Hi @saovry - I think this extension is wrong for your desired funktion. You can create a content override for it. After readmore you only show adsense and put the fulltext into a display:none; container, which will be revealed by the second click. If you are interested in a custom development contact me for a quote at coolcat-creations.com
